### ISSUE TITLE
TypeORM Multiple connections 구현

### ISSUE THREAD

**Issue by parkgang** [belf-kr/todo-service#16]
prod 환경은 Mysql Replication 되어있습니다. 이에 따라 [해당 문서](https://typeorm.io/#/multiple-connections/replication)를 참고하여 구현해주세요.
local, qa 일 때는 master, slave 에 같은 호스트 주소를 넣고 prod는 다르게 하는 전략을 사용하면 될 꺼 같습니다.
더 좋은 방법이 있으면 적용해주세요.

**Comment by JP3Pe** [comment]
아래 링크 같은 글 참고해 추 후 DB 연결 정보를 ormconfig.ts 파일로 뺄 수 있는지 확인 해야함.

**Comment by parkgang** [comment]
> 아래 링크 같은 글 참고해 추 후 DB 연결 정보를 ormconfig.ts 파일로 뺄 수 있는지 확인 해야함.
> 
> 
> 
> https://stackoverflow.com/questions/51994541/nestjs-typeorm-use-two-or-more-databases/51995362#51995362

@JP3Pe 확인된건가요?

**Comment by JP3Pe** [comment]
@JP3Pe 해당 글에는 
1. 다중 연결인 경우 따로 파일을 빼면 버그가 생긴다는 답변
2. name: "연결 이름" 형식으로 하면 된다는 답변

2가지가 존재하는데, 위 2번 방법으로 시도했을 때 TypeORM 에서 DB 오류가 발생했습니다.
해당 방법으로 하려는 중 제가 무언가 놓친 부분이 있을 수 있어 추 후 시간을 내어 재확인이 필요합니다.

만약 가능하다 해도 제가 잘못한 부분을 찾으려 어제, 오늘 많은 시간을 소비한 터라 우선 작동이 된다고 확인한 app.module.ts 파일 내 삽입하는 방식으로 커밋을 진행했습니다.

**Comment by parkgang** [comment]
@JP3Pe app.module의 인젝션 부분에 미리 설정한 typeorm root의 connection중 name에 맞게 get에서 연결을 시도한다는 건가요?

**Comment by JP3Pe** [comment]
@parkgang 제가 nestjs 공식 홈페이지의 샘플 코드를 보고 이해한 바로는 그렇습니다.

provider 부분을 제가 정의 해서 localConnection 문자열을 기준으로 연결 한다고 이해했습니다.
(해당 문자열을 변경하며 DB 연결 여부 정도로 테스트 했습니다.)

**Comment by parkgang** [comment]
@JP3Pe 네, 일단 자세한 메커니즘은 제가 집가서 확인해보도록 하겠습니다. API의 경우 복잡한 테이블에 시도하시지 마시고 간단한 테이블로 시도해주세요 prod의 경우 master, slave 확인을 위해서 생성 쿼리 100회 읽기 쿼리 100회 나누어 진행하려고 합니다. 잘못 connection 되었다면 생성 쿼리 도중 에러를 뱉을 것입니다.

**Comment by JP3Pe** [comment]
@parkgang 보다 디테일한 내용은 API 본 다음 재 확인 하도록 하겠습니다.

**Comment by JP3Pe** [comment]
Multiple Connection(Local, QA, Product)환경에 대한 커밋을 CRUD API, npm .env 설정 후 재작성 하기 위해 해당 이슈를 다시 열었습니다.

**Comment by JP3Pe** [comment]
기존에는 local, qa, prod 환경 구분을 위해 json 으로 구성된 각 연결 정보에 name key 값으로 DB 연결 정보를 주입 받으려고 했었지만, .env 사용해 각 환경에서 적절한 값을 동적으로 주입 받는 식으로 수정해 해당 부분이 필요 없어졌습니다.
