### ISSUE TITLE
TypeORM을 사용할 때 참고가 될 수 있는 DB Table, ORM 쿼리 코드 생성

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/todo-service#39]
TypeORM을 사용하려면 Google 검색을 통한 각종 질의 응답이나, 공식 홈페이지 등을 참고해 큰 문제 없이 원하는 바를 작성할 수 있음.
하지만, 보다 빠른 작업을 위해 로컬에서 무언가 참고를 할 수 있는 예제가 존재한다면 매우 좋을 것임.

- [x] PK만 존재하는 테이블에 대한 CRUD 샘플 생성
- [x] FK도 존재하는 테이블에 대한 CRUD 샘플 생성

**Comment by JP3Pe** [comment]
# 생성해야 하는 기능

## PK만 존재하는 테이블
1. DB에 Insert 시 HTTP 포멧 및 예상 반환값
2. DB에 특정 행 1개 SELECT시 HTTP 포멧 및 예상 반환값
3. DB에 특정 행 여러개 SELECT시 HTTP 포맷 및 예상 반환값
4. DB에 특정 테이블에 대한 모든 값을 리스트 형식으로 요청 시 HTTP 포맷 및 예상 반환값
5. DB에 특정 행 1개 DELETE 시 HTTP 포멧 및 예상 반환값
6. DB에 특정 행 여러개 DELTE 시 HTTP 포멧 및 예상 반환값
7. DB에 특정 행 1개 UPDATE 시 HTTP 포멧 및 예상 반환값

FK도 존재하는 테이블과 FK->PK테이블 간 Join 등의 기능 리스트(?)는 다른 댓글에서 언급할 계획입니다.

@parkgang 예제 검토 부탁드립니다.

**Comment by parkgang** [comment]
@JP3Pe 서면으로 컨택되었습니다.

**Comment by JP3Pe** [comment]
# 생성해야 하는 기능

## PK만 존재하는 테이블
1. DB에 특정 행 1개 C/R/U/D 할 경우 HTTP 포멧 및 예상 반환값
2. DB에 특정 행 여러개 C/R/U/D 할 HTTP 포맷 및 예상 반환값
3. DB에 특정 테이블에 대한 모든 값을 R/D 할 HTTP 포맷 및 예상 반환값

검토 결과 위로 결정되었습니다.
