### ISSUE TITLE
example-upper 일부 컬럼이 정상적으로 생성되지 않습니다.

### ISSUE THREAD

**Issue by parkgang** [belf-kr/todo-service#48]
# 시나리오

1. 아래의 api 요청 결과 nullable_int, default_double 가 정상적으로 insert 되지 않았습니다.
2. 버그 수정은 migration branch에서 바로 해주세요

# API 요청 값

```http
Content-Type: application/json

[
    {
        "title": "값이 정상적으로 등록되지 않습니다.",
        "content": "숫자가 정상적으로 input 되지 않습니다.",
        "nullable_int": 30,
        "default_double": 50.2
    }
]
```

# 생성된 값
   
![image](https://user-images.githubusercontent.com/63892989/120881482-4e453e00-c60c-11eb-8b2a-988d07cb8e16.png)

**Comment by JP3Pe** [comment]
@parkgang 해당 이슈는 nullable_int, default_double 이라는 이름의 속성값이 example-upper.entity.ts 파일 내 존재하지 않아 발생 한 문제로 보입니다.
해당 이슈는 0.2.0의 이슈에서 해결을 해 두었습니다. origin/feature/jp3pe 최신 커밋 기준으로 동일 테스트를 한번 진행 부탁드립니다.

0.1.0을 가리키고 있는 feature/migration 브랜치는 수정 전 커밋을 가리키고 있어 0.1.0 을 배포했을 때 정상 동작이 되지 않는 문제가 발생할 것 같네요.
최신 커밋 및 해당 커밋 이력이 해결했다고 표시된 이슈들을 0.2.0 에서 0.1.0 마일스톤으로 이동할까요?

**Comment by JP3Pe** [comment]
@parkgang json 요청 값 중 속성값의 이름을 nullableInt, defaultDouble 으로 변경하면 작동 될 것으로 예상됩니다.

**Comment by parkgang** [comment]
> @parkgang 해당 이슈는 nullable_int, default_double 이라는 이름의 속성값이 example-upper.entity.ts 파일 내 존재하지 않아 발생 한 문제로 보입니다.
> 해당 이슈는 0.2.0의 이슈에서 해결을 해 두었습니다. origin/feature/jp3pe 최신 커밋 기준으로 동일 테스트를 한번 진행 부탁드립니다.
> 
> 0.1.0을 가리키고 있는 feature/migration 브랜치는 수정 전 커밋을 가리키고 있어 0.1.0 을 배포했을 때 정상 동작이 되지 않는 문제가 발생할 것 같네요.
> 최신 커밋 및 해당 커밋 이력이 해결했다고 표시된 이슈들을 0.2.0 에서 0.1.0 마일스톤으로 이동할까요?

@JP3Pe `v0.1.0` 에서 수정되어야 합니다. `migration branch` 로 수정 후 노티해주세요.

**Comment by JP3Pe** [comment]
@parkgang 버그가 수정된 최신 작업물을 feature/migration 브랜치로 merge 했습니다. pull 하신 다음 확인 부탁드립니다.

**Comment by parkgang** [comment]
> @parkgang 버그가 수정된 최신 작업물을 feature/migration 브랜치로 merge 했습니다. pull 하신 다음 확인 부탁드립니다.

@JP3Pe 네, 어짜핀 api-gateway 테스트 하면서 qa될 것으로 기대합니다.

**Comment by JP3Pe** [comment]
QA 버전에서 테스트 완료 했습니다.
