### ISSUE TITLE
DB_SYNCHRONIZE 플래그에 따라서 TypeORM 작동 방식 탐구

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/todo-service#49]
DB를 prod 환경에 배포했을 때 스키마 변경이 일어날 것입니다.
스키마 변경 시 TypeORM을 사용한 스키마 변환이 어떤 식으로 일어나게 되는 지를 알아야 합니다.

# 시나리오

## DB_SYNCHRONIZE True 인 경우

- [ ] 데이터가 존재하는 테이블에 관한 엔티티 파일을 
   - [ ] 생성 한 경우 테이블이 즉시 생성되는가?
   - [ ] 삭제 한 경우 테이블이 즉시 삭제되는가?
- [ ] 테이블 내 컬럼명을 변경하는 경우 어떻게 되는가?
- [ ] 테이블 내 컬럼의 속성을 변경하는 경우 어떻게 되는가?

## DB_SYNCHRONIZE False 인 경우

- [ ] 데이터가 존재하는 테이블에 관한 엔티티 파일을 
    - [ ] 생성 한 경우 테이블이 즉시 생성되는가?
    - [ ] 삭제 한 경우 테이블이 즉시 삭제되는가?
- [ ] 테이블 내 컬럼명을 변경하는 경우 어떻게 되는가?
- [ ] 테이블 내 컬럼의 속성을 변경하는 경우 어떻게 되는가?
- [ ] 자동으로 마이그레이션 되는 case가 있는가?
   > 예를 들어 테이블 **생성**의 경우는 False으로 하더라도 생성됩니다.

## 테이블 수정 및 삭제가 안되는 경우

- [ ] migration 도구를 사용해 테이블을 
    - [ ] 생성하는 경우 어떻게 되고 어떻게 하는가?
    - [ ] 삭제하는 경우 어떻게 되고 어떻게 하는가?
- [ ] migration 도구를 사용해 컬럼명을 변경하는 경우 어떻게 되고 어떻게 하는가?
- [ ] migration 도구를 사용해 컬럼의 속성을 변경하는 경우 어떻게 작동되고 어떻게 하는가?

**Comment by parkgang** [comment]
@JP3Pe 부족한 내용을 추가하였습니다. 테스트 후 해당 이슈에 답글 달아주세요.

**Comment by JP3Pe** [comment]
데이터가 존재하는 테이블에 관한 엔티티 파일을 삭제 한 경우 테이블이 즉시 삭제되지 않는다.

**Comment by JP3Pe** [comment]
존재하는 테이블에 컬럼을 추가 한 경우 웹 서버 재부팅 시 컬럼이 추가된다.

**Comment by JP3Pe** [comment]
존재하는 테이블의 컬럼을 엔티티에서 삭제 한 경우 해당 컬럼과 데이터가 전부 삭제된다.

**Comment by JP3Pe** [comment]
## DB_SYNCHRONIZE True 인 경우
### 컬럼명 변경 한 경우
컬럼명이 즉시 변경된다.
### 컬럼의 속성을 변경 한 경우
제약 조건등을 변경 한 경우 잔존 데이터등이 없는 경우 즉시 변경되고, 존재하는 경우 TypeORM 에러 발생한다.
컬럼의 자료형은 변경되지 않는다.

## DB_SYNCHRONIZE False 인 경우
### 엔티티 파일을 생성 한 경우 
테이블이 즉시 생성되었다.
### 엔티티 파일을 삭제 한 경우
테이블이 삭제되지 않았다.
### 테이블 내 컬럼명을 변경 한 경우
컬럼명이 즉시 변경되었다.
### 테이블 내 컬럼의 속성을 변경 한 경우
자료형을 변경 한 경우 자동 변경이 되지 않았다.
컬럼의 제약 조건도 변경되지 않는다.

**Comment by JP3Pe** [comment]
Notion 작업 문서에 동일 내용이 존재하기 때문에 close합니다.
