### ISSUE TITLE
[오늘 할일] 잔디 심기 데이터

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#57]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/Spec-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#759f1588aee948bd82e45f73feb5ee20
- 기능 : 잔디 심기 컴포넌트에 들어갈 데이터입니다. 
### 조건
- 데이터의 총 개수는 23(6개월에서 1개의 주를 뺸 주의 수) * 7(요일 7개) + 오늘요일(일요일 부터 시작)
- - ex) 23 * 7 * 3 => 오늘이 화요일이라는 의미
- 사용자가 6개월 동안 한일의 개수를 하루 단위로 카운트 해야합니다.

**Comment by JP3Pe** [comment]
일정을 Notion에서 관리하는거로 이관한 뒤 이 이슈는 우선순위에서 밀려나 close합니다.
