### ISSUE TITLE
[코스 리스트] 해당 유저의 전체 코스의 like 개수

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#59]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/Spec-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#cd46894316444736926f63ed9436fa4b
- 기능 : [코스 리스트] 해당하는 유저의 전체 코스의 like 개수를 계산하여 가져옵니다.
### 조건
- belf와 같이 가져오려고 하면 안됨 컴포넌트가 다르기 때문에 요청이 다름

**Comment by JP3Pe** [comment]
SNS적 기능이 현재 우선순위에서 밀려있기 때문에 우선 close합니다.
