### ISSUE TITLE
[코스 리스트] 해당하는 유저의 전체 코스의 belf(코스 참조) 개수

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#60]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/Spec-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#6bd78cd70ed6435bb1e620291e701346
- 기능 : [코스 리스트] 해당하는 유저의 전체 코스의 belf(코스 참조) 개수
### 조건
- like와 같이 가져오려고 하면 안됨 컴포넌트가 다르기 때문에 요청이 다름

**Comment by JP3Pe** [comment]
SNS적 기능의 구현 우선순위가 현 시점에서 낮기 때문에 이슈를 close합니다.
