### ISSUE TITLE
[코스 리스트] 코스 리스트

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#61]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/Spec-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#01570a553bbc41a68f32ea36fdb227f3
- 기능 : [코스 리스트] 코스 리스트를 가져옵니다.
### 조건
- x

**Comment by JP3Pe** [comment]
@algo2000 코스의 리스트를 가져오는 기능에 어떤 검색기능 같은게 필요하나요?

**Comment by JP3Pe** [comment]
추 후 검색을 태그나 유저 Id 값으로 진행 해야 합니다.

**Comment by JP3Pe** [comment]
@algo2000 검색 기능 등의 부분은 아직 구현되지 않았습니다만, 추 후 새로운 이슈로 등록해주세요.
