### ISSUE TITLE
[코스 추가] 코스의 색상을 주기 위한 색상 리스트

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#62]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/Spec-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#01cab20c5383418cb7d7c41d8bf1aedd
- 기능 : [코스 추가] 코스의 색상을 주기 위한 색상 리스트를 가져옵니다.
### 조건
- 정해진 색상을 DB상에 넣어두고 해당 데이터를 읽어 가져옵니다.

**Comment by algo2000** [comment]
> @algo2000 링크하신 notion 페이지의 내용이 코스 추가/Response/color_table 내 색상값 JSON 코드인가요?

해당 json에 있는 색상 코드값을 DB에 넣어두신다음 사용하시면 됩니다.

**Comment by JP3Pe** [comment]
@algo2000
```json
{
  "color_list": [
    "#FF8484",
    "#FFD484",
    "#84FFD0",
    "#84D0FD",
    "#84AAFF",
    "#FF84B8",
    "#DF5BFF",
    "#8D84FB",
    "#84FFF6",
    "#D9FF84"
  ]
}
```

색상값을 해당 형태로 받아와야 한다고 이해했는데, notion 링크 클릭 시 해당 화면을 보여 주었다가 위 쪽의 (아래 코드가 나온)화면으로 이동해서 확인차 여쭤봤습니다.
````json{
  "todo_list": [
    {
      "reminder_id": "3F2504E0-4F89-11D3-9A0C0305E82C3301",
      "reminder_title": "문법 공부",
      "course_title": "영어 공부하기",
      "color": "#FF8484"
    },
    {
      "reminder_id": "3F2504E0-4F89-11D3-9A0C0305E82C3301",
      "reminder_title": "문법 공부",
      "course_title": "영어 공부하기",
      "color": "#FF8484"
    },
    {
      "reminder_id": "3F2504E0-4F89-11D3-9A0C0305E82C3301",
      "reminder_title": "문법 공부",
      "course_title": "영어 공부하기",
      "color": "#FF8484"
    }
  ]
}
````

**Comment by algo2000** [comment]
> @algo2000
> 
> ```json
> {
>   "color_list": [
>     "#FF8484",
>     "#FFD484",
>     "#84FFD0",
>     "#84D0FD",
>     "#84AAFF",
>     "#FF84B8",
>     "#DF5BFF",
>     "#8D84FB",
>     "#84FFF6",
>     "#D9FF84"
>   ]
> }
> ```
> 
> 색상값을 해당 형태로 받아와야 한다고 이해했는데, notion 링크 클릭 시 해당 화면을 보여 주었다가 위 쪽의 (아래 코드가 나온)화면으로 이동해서 확인차 여쭤봤습니다.
> 
> ```
>   "todo_list": [
>     {
>       "reminder_id": "3F2504E0-4F89-11D3-9A0C0305E82C3301",
>       "reminder_title": "문법 공부",
>       "course_title": "영어 공부하기",
>       "color": "#FF8484"
>     },
>     {
>       "reminder_id": "3F2504E0-4F89-11D3-9A0C0305E82C3301",
>       "reminder_title": "문법 공부",
>       "course_title": "영어 공부하기",
>       "color": "#FF8484"
>     },
>     {
>       "reminder_id": "3F2504E0-4F89-11D3-9A0C0305E82C3301",
>       "reminder_title": "문법 공부",
>       "course_title": "영어 공부하기",
>       "color": "#FF8484"
>     }
>   ]
> }
> ```

```
{
  "color_list": [
    "#FF8484",
    "#FFD484",
    "#84FFD0",
    "#84D0FD",
    "#84AAFF",
    "#FF84B8",
    "#DF5BFF",
    "#8D84FB",
    "#84FFF6",
    "#D9FF84"
  ]
}
```
이게 맞습니다.
