### ISSUE TITLE
[코스 추가] 새로운 코스 추가

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#63]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/Spec-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#cd7afe53a9be48b39bc41b8d3e401e19
- 기능 : [코스 추가] 새로운 코스를 추가합니다. 
### 조건
- X

**Comment by JP3Pe** [comment]
@algo2000 코스에 대해서 넘겨주는 색상 코드 값은 DB에 존재하는지 여부를 front 에서 확인 후 념겨주나요?
아니면 제가 체크해야 하나요?
