### ISSUE TITLE
[코스 리스트] 코스 삭제

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#74]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : 
- 기능 : [코스 리스트] 선택된 코스를 삭제합니다.
### 조건
- 코스의 아이디 값을 인자로 넘겨주면 해당 아이디 값의 코스를 삭제합니다.

**Comment by JP3Pe** [comment]
코스를 삭제할 때 type 형식을 entity class 형식의 객체를 생성하는 방법을 찾아야 하는 문제가 있어 이슈를 재오픈합니다.

**Comment by algo2000** [comment]
전체 코스 조회 시 코스의 아이디 값이 오지 않아 코스 삭제가 불가능 합니다. 확인해 주세요

`https://api-gateway.qa.belf.xyz/todo/get-all-courses`
id 추가해주셔야합니다.

**Comment by JP3Pe** [comment]
@algo2000 id 값을 가져오지 못 하는 문제를 수정했습니다.
