### ISSUE TITLE
[한일 디테일] 한일 정보 가져오기

### ISSUE THREAD

**Issue by algo2000** [belf-kr/todo-service#80]
- 엔드 포인트 : (기입 필요)
- 데이터 형태 : https://www.notion.so/todo-service-1a7cb4cc2fc349e7a6c3b9c6f78a22d5#28d16f1a65974d37931aed7af00457b3
- 기능 : [한일 디테일] 한일 디테일 정보를 줍니다
### 조건
- 한일 id를 보내면 해당 한일의 디테일 정보를 응답해줍니다.

**Comment by JP3Pe** [comment]
@algo2000 detail 내 option 등의 key 정보는 무엇인가요? DB 설계 시에는 확인하지 못한 항목 같습니다.

**Comment by algo2000** [comment]
@JP3Pe 콘텐츠 안쪽 데이터는 저만 활용하는갓으로 그부분 데이터는 그냥 db에 넣어주시면 됩니다 그리고 조회할때 그대로 반환하면 됩니다

**Comment by JP3Pe** [comment]
@algo2000 네 문자열로 취급하겠습니다.

**Comment by JP3Pe** [comment]
@algo2000 한 일 에 해당되는 객체와, 그 객체가 속해있는 course 정보도 함께 넘겨 주어야 하나요?
