### ISSUE TITLE
Controller listen URL Rest ful 하게 변경

### ISSUE THREAD

**Issue by JP3Pe** [belf-kr/todo-service#84]
기존 URL endpoint 들은 rest ful 하지 않고 작업자 임의로 정한 URL 들이 사용되었다.
이를 Restful 한 웹 아키텍처를 적극 활용해 웹 표준과 궤를 같이 해야할 필요가 존재한다.

**Comment by Seungup** [comment]
이슈가 중복되어있으므로 해당 이슈를 종료합니다.

 https://github.com/belf-kr/todo-service/issues/85
