### ISSUE TITLE
Restful API의 제약조건 중 쉽게 적용할 수 있는 조건을 달성합니다.

### ISSUE THREAD

**Issue by Seungup** [belf-kr/todo-service#85]
Rest API의 Self-Description, HATEOAS를 만족하도록 컨트롤러 설계

-- 이하 추가 --
기존 URL endpoint 들은 rest ful 하지 않고 작업자 임의로 정한 URL 들이 사용되었다.
이를 Restful 한 웹 아키텍처를 적극 활용해 웹 표준과 궤를 같이 해야할 필요가 존재한다.

**Comment by JP3Pe** [comment]
self, description, HATEOAS 조건을 만족하는 RESTFUL API는 현 시점에서 완전히 구현하기가 어려운 만큼
아래의 RESTFUL API 조건을 만족하게 HTTP API를 생성합니다.

1. 표현을 하고자 하는 객체를 URI에 복수형으로 서술
2. 값을 알고자 하는 객체에 대한 검색 조건등은 질의 문자열로 처리
3. HTTP method 사용해 동작을 표현할 것
4. HTTP 응답 코드를 적절하게 사용해 서버에서의 처리 결과을 알 수 있게 할 것
5. 후행 슬래시 URI(예: https://www.foo.var/)의 마지막 / 문자열을 없는 버전의 URI로 리다이렉트 할 것

**Comment by JP3Pe** [comment]
후행 슬래시 처리는 API 프로젝트에서 처리했습니다.
[API](https://github.com/belf-kr/api-gateway/issues/37l)
